import Link from "next/link";
import { asc, eq, sql as raw } from "drizzle-orm";

import { setTransportStatus } from "@/app/actions/equipment";
import { Badge, Button, EmptyState, PageHeader } from "@/components/ui/primitives";
import { Sheet, TBody, TD, TFootRow, TH, THead, TR, Table } from "@/components/ui/table";
import { Money } from "@/components/ui/gauge";
import { db } from "@/lib/db";
import { objectives, transports, users, workUnits } from "@/lib/db/schema";
import {
  TRANSPORT_KIND_LABEL,
  TRANSPORT_STATUS_LABEL,
  TRANSPORT_STATUS_TONE,
  formatDay,
  today as todayIso,
} from "@/lib/equipment";
import { fromDb } from "@/lib/money";
import { canSeePrices } from "@/lib/permissions";
import { requireSession } from "@/lib/session";

export const dynamic = "force-dynamic";

const NEXT_STATUS: Record<string, { to: string; label: string } | null> = {
  ceruta: { to: "planificata", label: "Planifică" },
  planificata: { to: "efectuata", label: "Marchează efectuată" },
  efectuata: null,
  anulata: null,
};

export default async function TransporturiPage({
  searchParams,
}: {
  searchParams: Promise<{ stare?: string; tip?: string }>;
}) {
  const session = await requireSession();
  const sp = await searchParams;
  const showPrices = canSeePrices(session.role);
  const today = todayIso();

  const filters = [];
  if (sp.stare) filters.push(raw`${transports.status} = ${sp.stare}`);
  if (sp.tip) filters.push(raw`${transports.kind} = ${sp.tip}`);

  const [rows, counts] = await Promise.all([
    db
      .select({
        transport: transports,
        fromObjective: objectives,
        unit: workUnits,
        requester: users,
      })
      .from(transports)
      .leftJoin(objectives, eq(transports.fromObjectiveId, objectives.id))
      .leftJoin(workUnits, eq(transports.workUnitId, workUnits.id))
      .leftJoin(users, eq(transports.requestedBy, users.id))
      .where(filters.length ? raw`${raw.join(filters, raw` and `)}` : undefined)
      // cererile sus, apoi cronologic: coada se citește de sus în jos
      .orderBy(asc(transports.status), asc(transports.day))
      .limit(120),
    db.select({ status: transports.status, kind: transports.kind }).from(transports),
  ]);

  const auto = rows.filter((r) => r.transport.autoGenerated);
  const totalCost = rows.reduce((a, r) => a + fromDb(r.transport.cost), 0);
  const byStatus = (s: string) => counts.filter((c) => c.status === s).length;

  return (
    <div className="space-y-6">
      <PageHeader
        eyebrow="Resurse"
        title="Transporturi"
        meta="O coadă centrală, nu un dosar per șantier. Transporturile generate automat — din comenzi și din rezervări de utilaje — intră singure aici, fără să le ceară nimeni."
      />

      <div className="grid gap-3 md:grid-cols-4">
        <Stat label="Cerute" value={String(byStatus("ceruta"))} hint="așteaptă planificare" tone={byStatus("ceruta") ? "warn" : undefined} />
        <Stat label="Planificate" value={String(byStatus("planificata"))} hint="au dată și traseu" />
        <Stat label="Efectuate" value={String(byStatus("efectuata"))} />
        <Stat
          label="Generate automat"
          value={String(auto.length)}
          hint="din comenzi și planificări de utilaj"
        />
      </div>

      <div className="flex flex-wrap items-center gap-1.5">
        <Chip href="/transporturi" active={!sp.stare && !sp.tip} label="Tot" />
        <span aria-hidden className="mx-1 h-4 w-px bg-rule" />
        {Object.entries(TRANSPORT_STATUS_LABEL).map(([key, label]) => (
          <Chip
            key={key}
            href={sp.stare === key ? "/transporturi" : `/transporturi?stare=${key}`}
            active={sp.stare === key}
            label={`${label} · ${byStatus(key)}`}
          />
        ))}
        <span aria-hidden className="mx-1 h-4 w-px bg-rule" />
        {Object.entries(TRANSPORT_KIND_LABEL).map(([key, label]) => (
          <Chip
            key={key}
            href={sp.tip === key ? "/transporturi" : `/transporturi?tip=${key}`}
            active={sp.tip === key}
            label={label}
          />
        ))}
      </div>

      {rows.length === 0 ? (
        <EmptyState
          title="Coada e goală"
          hint="Transporturile intră din trei locuri: cerute de pe șantier, generate de o comandă de material sau generate de rezervarea unui utilaj."
        />
      ) : (
        <Sheet>
          <Table>
            <THead>
              <TR>
                <TH>Cod</TH>
                <TH>Tip</TH>
                <TH>Ziua</TH>
                <TH>De la</TH>
                <TH>Către</TH>
                <TH>Unitate de lucru</TH>
                <TH>Sursă</TH>
                <TH>Stare</TH>
                {showPrices ? <TH numeric>Cost</TH> : null}
                <TH />
              </TR>
            </THead>
            <TBody>
              {rows.map(({ transport, fromObjective, unit }) => {
                const next = NEXT_STATUS[transport.status];
                const late = transport.status === "ceruta" && transport.day < today;
                return (
                  <TR key={transport.id}>
                    <TD className="font-medium">{transport.code}</TD>
                    <TD muted>{TRANSPORT_KIND_LABEL[transport.kind]}</TD>
                    <TD className={late ? "text-over" : undefined}>
                      {formatDay(transport.day)}
                      {late ? <span className="block text-micro">întârziat</span> : null}
                    </TD>
                    <TD muted className="max-w-40 truncate">
                      {transport.fromText ?? fromObjective?.name ?? "—"}
                    </TD>
                    <TD muted className="max-w-40 truncate">
                      {transport.toText ?? "—"}
                    </TD>
                    <TD muted className="max-w-40 truncate">
                      {unit ? (
                        <Link href={`/lucrari/${unit.id}`} className="hover:text-blueprint">
                          {unit.code}
                        </Link>
                      ) : (
                        "—"
                      )}
                    </TD>
                    <TD muted>
                      {transport.autoGenerated ? (
                        <span className="text-blueprint">automat</span>
                      ) : (
                        "cerut"
                      )}
                    </TD>
                    <TD>
                      <Badge tone={TRANSPORT_STATUS_TONE[transport.status]}>
                        {TRANSPORT_STATUS_LABEL[transport.status]}
                      </Badge>
                    </TD>
                    {showPrices ? (
                      <TD numeric muted>
                        <Money value={fromDb(transport.cost)} unit={null} />
                      </TD>
                    ) : null}
                    <TD>
                      {next ? (
                        <form action={setTransportStatus}>
                          <input type="hidden" name="transportId" value={transport.id} />
                          <input type="hidden" name="status" value={next.to} />
                          <Button type="submit" size="sm">
                            {next.label}
                          </Button>
                        </form>
                      ) : null}
                    </TD>
                  </TR>
                );
              })}
            </TBody>
            {showPrices ? (
              <tfoot>
                <TFootRow>
                  <TD colSpan={8}>{rows.length} transporturi</TD>
                  <TD numeric>
                    <Money value={totalCost} unit={null} />
                  </TD>
                  <TD />
                </TFootRow>
              </tfoot>
            ) : null}
          </Table>
        </Sheet>
      )}
    </div>
  );
}

function Stat({
  label,
  value,
  hint,
  tone,
}: {
  label: string;
  value: string;
  hint?: string;
  tone?: "warn";
}) {
  return (
    <div className="border border-rule-strong bg-sheet px-4 py-3">
      <div className="eyebrow mb-1">{label}</div>
      <div
        className={`tabular font-narrow text-[1.5rem] font-semibold leading-none ${
          tone === "warn" ? "text-warn" : "text-ink"
        }`}
      >
        {value}
      </div>
      {hint ? <div className="mt-1 text-micro text-ink-3">{hint}</div> : null}
    </div>
  );
}

function Chip({ href, active, label }: { href: string; active: boolean; label: string }) {
  return (
    <Link
      href={href}
      className={`rounded-[3px] border px-2 py-0.5 text-tiny transition-colors ${
        active
          ? "border-blueprint bg-blueprint text-white"
          : "border-rule-strong bg-sheet text-ink-2 hover:bg-sunk hover:text-ink"
      }`}
    >
      {label}
    </Link>
  );
}
